# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from quadruped/LegStamped.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import quadruped.msg
import std_msgs.msg

class LegStamped(genpy.Message):
  _md5sum = "25edac3637c8888c0a44c3649cad03ef"
  _type = "quadruped/LegStamped"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

float64 theta
float64 beta

motor motor_r
motor motor_l

force force
impedance impedance

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: quadruped/motor
float64 angle
float64 twist
float64 torque
float64 kp
float64 ki
float64 kd
================================================================================
MSG: quadruped/force
float64 pose_x
float64 pose_y
float64 force_x
float64 force_y
================================================================================
MSG: quadruped/impedance
float64 M_x
float64 M_y
float64 K0_x
float64 K0_y
float64 D_x
float64 D_y
float64 adaptive_kp_x
float64 adaptive_kp_y
float64 adaptive_ki_x
float64 adaptive_ki_y
float64 adaptive_kd_x
float64 adaptive_kd_y"""
  __slots__ = ['header','theta','beta','motor_r','motor_l','force','impedance']
  _slot_types = ['std_msgs/Header','float64','float64','quadruped/motor','quadruped/motor','quadruped/force','quadruped/impedance']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,theta,beta,motor_r,motor_l,force,impedance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LegStamped, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.theta is None:
        self.theta = 0.
      if self.beta is None:
        self.beta = 0.
      if self.motor_r is None:
        self.motor_r = quadruped.msg.motor()
      if self.motor_l is None:
        self.motor_l = quadruped.msg.motor()
      if self.force is None:
        self.force = quadruped.msg.force()
      if self.impedance is None:
        self.impedance = quadruped.msg.impedance()
    else:
      self.header = std_msgs.msg.Header()
      self.theta = 0.
      self.beta = 0.
      self.motor_r = quadruped.msg.motor()
      self.motor_l = quadruped.msg.motor()
      self.force = quadruped.msg.force()
      self.impedance = quadruped.msg.impedance()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_30d().pack(_x.theta, _x.beta, _x.motor_r.angle, _x.motor_r.twist, _x.motor_r.torque, _x.motor_r.kp, _x.motor_r.ki, _x.motor_r.kd, _x.motor_l.angle, _x.motor_l.twist, _x.motor_l.torque, _x.motor_l.kp, _x.motor_l.ki, _x.motor_l.kd, _x.force.pose_x, _x.force.pose_y, _x.force.force_x, _x.force.force_y, _x.impedance.M_x, _x.impedance.M_y, _x.impedance.K0_x, _x.impedance.K0_y, _x.impedance.D_x, _x.impedance.D_y, _x.impedance.adaptive_kp_x, _x.impedance.adaptive_kp_y, _x.impedance.adaptive_ki_x, _x.impedance.adaptive_ki_y, _x.impedance.adaptive_kd_x, _x.impedance.adaptive_kd_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.motor_r is None:
        self.motor_r = quadruped.msg.motor()
      if self.motor_l is None:
        self.motor_l = quadruped.msg.motor()
      if self.force is None:
        self.force = quadruped.msg.force()
      if self.impedance is None:
        self.impedance = quadruped.msg.impedance()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 240
      (_x.theta, _x.beta, _x.motor_r.angle, _x.motor_r.twist, _x.motor_r.torque, _x.motor_r.kp, _x.motor_r.ki, _x.motor_r.kd, _x.motor_l.angle, _x.motor_l.twist, _x.motor_l.torque, _x.motor_l.kp, _x.motor_l.ki, _x.motor_l.kd, _x.force.pose_x, _x.force.pose_y, _x.force.force_x, _x.force.force_y, _x.impedance.M_x, _x.impedance.M_y, _x.impedance.K0_x, _x.impedance.K0_y, _x.impedance.D_x, _x.impedance.D_y, _x.impedance.adaptive_kp_x, _x.impedance.adaptive_kp_y, _x.impedance.adaptive_ki_x, _x.impedance.adaptive_ki_y, _x.impedance.adaptive_kd_x, _x.impedance.adaptive_kd_y,) = _get_struct_30d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_30d().pack(_x.theta, _x.beta, _x.motor_r.angle, _x.motor_r.twist, _x.motor_r.torque, _x.motor_r.kp, _x.motor_r.ki, _x.motor_r.kd, _x.motor_l.angle, _x.motor_l.twist, _x.motor_l.torque, _x.motor_l.kp, _x.motor_l.ki, _x.motor_l.kd, _x.force.pose_x, _x.force.pose_y, _x.force.force_x, _x.force.force_y, _x.impedance.M_x, _x.impedance.M_y, _x.impedance.K0_x, _x.impedance.K0_y, _x.impedance.D_x, _x.impedance.D_y, _x.impedance.adaptive_kp_x, _x.impedance.adaptive_kp_y, _x.impedance.adaptive_ki_x, _x.impedance.adaptive_ki_y, _x.impedance.adaptive_kd_x, _x.impedance.adaptive_kd_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.motor_r is None:
        self.motor_r = quadruped.msg.motor()
      if self.motor_l is None:
        self.motor_l = quadruped.msg.motor()
      if self.force is None:
        self.force = quadruped.msg.force()
      if self.impedance is None:
        self.impedance = quadruped.msg.impedance()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 240
      (_x.theta, _x.beta, _x.motor_r.angle, _x.motor_r.twist, _x.motor_r.torque, _x.motor_r.kp, _x.motor_r.ki, _x.motor_r.kd, _x.motor_l.angle, _x.motor_l.twist, _x.motor_l.torque, _x.motor_l.kp, _x.motor_l.ki, _x.motor_l.kd, _x.force.pose_x, _x.force.pose_y, _x.force.force_x, _x.force.force_y, _x.impedance.M_x, _x.impedance.M_y, _x.impedance.K0_x, _x.impedance.K0_y, _x.impedance.D_x, _x.impedance.D_y, _x.impedance.adaptive_kp_x, _x.impedance.adaptive_kp_y, _x.impedance.adaptive_ki_x, _x.impedance.adaptive_ki_y, _x.impedance.adaptive_kd_x, _x.impedance.adaptive_kd_y,) = _get_struct_30d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_30d = None
def _get_struct_30d():
    global _struct_30d
    if _struct_30d is None:
        _struct_30d = struct.Struct("<30d")
    return _struct_30d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
