// Generated by gencpp from file quadruped/motor.msg
// DO NOT EDIT!


#ifndef QUADRUPED_MESSAGE_MOTOR_H
#define QUADRUPED_MESSAGE_MOTOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace quadruped
{
template <class ContainerAllocator>
struct motor_
{
  typedef motor_<ContainerAllocator> Type;

  motor_()
    : angle(0.0)
    , twist(0.0)
    , torque(0.0)
    , kp(0.0)
    , ki(0.0)
    , kd(0.0)  {
    }
  motor_(const ContainerAllocator& _alloc)
    : angle(0.0)
    , twist(0.0)
    , torque(0.0)
    , kp(0.0)
    , ki(0.0)
    , kd(0.0)  {
  (void)_alloc;
    }



   typedef double _angle_type;
  _angle_type angle;

   typedef double _twist_type;
  _twist_type twist;

   typedef double _torque_type;
  _torque_type torque;

   typedef double _kp_type;
  _kp_type kp;

   typedef double _ki_type;
  _ki_type ki;

   typedef double _kd_type;
  _kd_type kd;





  typedef boost::shared_ptr< ::quadruped::motor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadruped::motor_<ContainerAllocator> const> ConstPtr;

}; // struct motor_

typedef ::quadruped::motor_<std::allocator<void> > motor;

typedef boost::shared_ptr< ::quadruped::motor > motorPtr;
typedef boost::shared_ptr< ::quadruped::motor const> motorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadruped::motor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadruped::motor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadruped::motor_<ContainerAllocator1> & lhs, const ::quadruped::motor_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle &&
    lhs.twist == rhs.twist &&
    lhs.torque == rhs.torque &&
    lhs.kp == rhs.kp &&
    lhs.ki == rhs.ki &&
    lhs.kd == rhs.kd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadruped::motor_<ContainerAllocator1> & lhs, const ::quadruped::motor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadruped

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadruped::motor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadruped::motor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadruped::motor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadruped::motor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadruped::motor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadruped::motor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadruped::motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89cf54e73edaf64e796e3374616d06a0";
  }

  static const char* value(const ::quadruped::motor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89cf54e73edaf64eULL;
  static const uint64_t static_value2 = 0x796e3374616d06a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadruped::motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadruped/motor";
  }

  static const char* value(const ::quadruped::motor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadruped::motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angle\n"
"float64 twist\n"
"float64 torque\n"
"float64 kp\n"
"float64 ki\n"
"float64 kd\n"
;
  }

  static const char* value(const ::quadruped::motor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadruped::motor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.twist);
      stream.next(m.torque);
      stream.next(m.kp);
      stream.next(m.ki);
      stream.next(m.kd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadruped::motor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadruped::motor_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "twist: ";
    Printer<double>::stream(s, indent + "  ", v.twist);
    s << indent << "torque: ";
    Printer<double>::stream(s, indent + "  ", v.torque);
    s << indent << "kp: ";
    Printer<double>::stream(s, indent + "  ", v.kp);
    s << indent << "ki: ";
    Printer<double>::stream(s, indent + "  ", v.ki);
    s << indent << "kd: ";
    Printer<double>::stream(s, indent + "  ", v.kd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADRUPED_MESSAGE_MOTOR_H
